version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - drei
  - foxact
  - generouted
  - gltf
  - importantimport
  - koota
  - masknet
  - moeru
  - moeru-ai
  - onreading
  - pixiv
  - pkgroll
  - sonarjs
  - thumbstick
ignoreWords: []
import: []
