version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - angvel
  - assetpack
  - bumpp
  - drei
  - foxact
  - generouted
  - gltf
  - hikari
  - importantimport
  - koota
  - linvel
  - lucide
  - masknet
  - metalness
  - mixamo
  - mixamorig
  - moeru
  - moeru-ai
  - msdf
  - onreading
  - orcust
  - PICO
  - pixiv
  - pkgroll
  - pmndrs
  - sonarjs
  - stdlib
  - subgoal
  - subgoals
  - thumbstick
  - tris
  - tsup
  - uikit
  - verts
  - vrma
  - vrmc
  - xsai
  - yuka
ignoreWords: []
import: []
