packages:
  - app
  - docs
  - packages/*

catalog:
  foxact: ^0.2.45

catalogs:
  react:
    '@generouted/react-router': ^1.20.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.3
    babel-plugin-react-compiler: &react-compiler 19.0.0-beta-714736e-20250131
    eslint-plugin-react-compiler: *react-compiler
    react: &react ^19.1.0
    react-dom: *react
    react-router: ^7.5.3

  three:
    '@pixiv/three-vrm': ^3.4.0
    '@pixiv/three-vrm-animation': ^3.4.0
    '@pmndrs/xr': &xr ^6.6.16
    '@react-three/drei': ^10.0.7
    '@react-three/fiber': ^9.1.2
    '@react-three/handle': *xr
    '@react-three/rapier': ^2.1.0
    '@react-three/uikit': &uikit ^0.8.16
    '@react-three/uikit-default': *uikit
    '@react-three/uikit-lucide': *uikit
    '@react-three/xr': *xr
    '@types/three': ^0.176.0
    three: ^0.176.0
    three-stdlib: ^2.36.0

  xsai:
    '@xsai/generate-text': &xsai ^0.2.2
    '@xsai/shared': *xsai
    '@xsai/shared-chat': *xsai

  yuka:
    '@recast-navigation/core': &recast-navigation ^0.39.0
    '@recast-navigation/three': *recast-navigation
    '@types/yuka': ^0.7.4
    yuka: ^0.7.8
