packages:
  - app
  - docs
  - packages/*

catalog:
  babel-plugin-react-compiler: 19.0.0-beta-714736e-20250131
  eslint-plugin-react-compiler: 19.0.0-beta-714736e-20250131

  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  react: ^19.0.0
  react-dom: ^19.0.0

  '@react-three/drei': ^10.0.0-rc.2
  '@react-three/fiber': ^9.0.0-rc.7
  '@types/three': ^0.173.0
  three: ^0.173.0

  '@pixiv/three-vrm': ^3.3.4
  '@pixiv/three-vrm-animation': ^3.3.4

  foxact: ^0.2.44
