packages:
  - app
  - docs
  - packages/*

overrides:
  react: catalog:react
  react-dom: catalog:react

catalog:
  foxact: ^0.2.49

catalogs:
  react:
    '@generouted/react-router': ^1.20.0
    '@types/react': ^19.1.7
    '@types/react-dom': ^19.1.6
    babel-plugin-react-compiler: 19.1.0-rc.2
    react: &react ^19.1.0
    react-dom: *react
    react-router: ^7.6.2

  three:
    '@pmndrs/xr': &xr ^6.6.17
    '@react-three/drei': ^10.1.2
    '@react-three/fiber': ^9.1.2
    '@react-three/handle': *xr
    '@react-three/rapier': ^2.1.0
    '@react-three/uikit': &uikit ^0.8.19
    '@react-three/uikit-default': *uikit
    '@react-three/uikit-lucide': *uikit
    '@react-three/xr': *xr
    '@types/three': ^0.177.0
    three: ^0.177.0
    three-stdlib: ^2.36.0

  vrm:
    '@pixiv/three-vrm': &three-vrm ^3.4.1
    '@pixiv/three-vrm-animation': *three-vrm
    wlipsync: ^1.2.1

  xsai:
    '@xsai/generate-speech': &xsai ^0.3.0-beta.3
    '@xsai/generate-text': *xsai
    '@xsai/generate-transcription': *xsai
    '@xsai/shared': *xsai
    '@xsai/shared-chat': *xsai

  yuka:
    '@types/yuka': ^0.7.4
    yuka: ^0.7.8
