packages:
  - docs
  - packages/*

catalog:
  babel-plugin-react-compiler: 19.0.0-beta-714736e-20250131
  eslint-plugin-react-compiler: 19.0.0-beta-714736e-20250131

  react: ^19.0.0
  react-dom: ^19.0.0
