packages:
  - app
  - docs
  - examples/*
  - packages/*

catalog:
  babel-plugin-react-compiler: 19.0.0-beta-714736e-20250131
  eslint-plugin-react-compiler: 19.0.0-beta-714736e-20250131

  '@generouted/react-router': ^1.20.0
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.3
  react: ^19.1.0
  react-dom: ^19.1.0
  react-router: ^7.5.3

  '@react-three/drei': ^10.0.7
  '@react-three/fiber': ^9.1.2
  '@react-three/handle': &xr ^6.6.16
  '@react-three/rapier': ^2.1.0
  '@react-three/uikit': &uikit ^0.8.16
  '@react-three/uikit-default': *uikit
  '@react-three/uikit-lucide': *uikit
  '@react-three/xr': *xr
  '@types/three': ^0.176.0
  three: ^0.176.0
  three-stdlib: ^2.36.0

  '@pixiv/three-vrm': ^3.4.0
  '@pixiv/three-vrm-animation': ^3.4.0

  foxact: ^0.2.45
